Repository FATEC-SJC-NoName/front-chat-app, pull requests merged in 2020-10, with the labels that each got.

#2 Atualizacao do front
  public/index.html
  src/components/ChatBox.vue
  src/main.js
Labels: enhancement

#3 adicionado funções aos botões
  src/components/ChatBox.vue
Labels: enhancement

#7 feature/axios-setup - WIP
  .browserslistrc
  .eslintrc.js
  .gitignore
  README.md
  babel.config.js
  cypress.json
  jest.config.js
  package-lock.json
  package.json
  public/img/icons/android-chrome-192x192.png
  public/img/icons/android-chrome-512x512.png
  public/img/icons/android-chrome-maskable-192x192.png
  public/img/icons/android-chrome-maskable-512x512.png
  public/img/icons/apple-touch-icon-120x120.png
  public/img/icons/apple-touch-icon-152x152.png
  public/img/icons/apple-touch-icon-180x180.png
  public/img/icons/apple-touch-icon-60x60.png
  public/img/icons/apple-touch-icon-76x76.png
  public/img/icons/apple-touch-icon.png
  public/img/icons/favicon-16x16.png
  public/img/icons/favicon-32x32.png
  public/img/icons/msapplication-icon-144x144.png
  public/img/icons/mstile-150x150.png
  public/img/icons/safari-pinned-tab.svg
  public/index.html
  public/robots.txt
  src/App.vue
  src/OldApp.vue
  src/components/ChatBox.vue
  src/components/Dashboard.vue
  src/components/HelloWorld.vue
  src/entities/chatModel.ts
  src/main.js
  src/main.ts
  src/registerServiceWorker.ts
  src/repositories/chatRepository.ts
  src/repositories/index.ts
  src/services/chatService.ts
  src/services/client.ts
  src/services/index.ts
  src/shims-tsx.d.ts
  src/shims-vue.d.ts
  src/store/index.ts
  tests/e2e/.eslintrc.js
  tests/e2e/plugins/index.js
  tests/e2e/specs/test.js
  tests/e2e/support/commands.js
  tests/e2e/support/index.js
  tests/unit/example.spec.ts
  tsconfig.json
Labels: bug, enhancement

#13 Feature/config vuetify
  .eslintrc.js
  .gitignore
  README.md
  babel.config.js
  cypress.json
  jest.config.js
  package-lock.json
  package.json
  public/img/icons/android-chrome-192x192.png
  public/img/icons/android-chrome-512x512.png
  public/img/icons/android-chrome-maskable-192x192.png
  public/img/icons/android-chrome-maskable-512x512.png
  public/img/icons/apple-touch-icon-120x120.png
  public/img/icons/apple-touch-icon-152x152.png
  public/img/icons/apple-touch-icon-180x180.png
  public/img/icons/apple-touch-icon-60x60.png
  public/img/icons/apple-touch-icon-76x76.png
  public/img/icons/apple-touch-icon.png
  public/img/icons/favicon-16x16.png
  public/img/icons/favicon-32x32.png
  public/img/icons/msapplication-icon-144x144.png
  public/img/icons/mstile-150x150.png
  public/img/icons/safari-pinned-tab.svg
  public/index.html
  public/robots.txt
  src/App.vue
  src/assets/logo.svg
  src/components/HelloWorld.vue
  src/components/index.ts
  src/components/message/Message.vue
  src/main.js
  src/main.ts
  src/models/chatModel.ts
  src/models/index.ts
  src/models/messageModel.ts
  src/modules/chat/Chat.vue
  src/modules/index.ts
  src/plugins/vuetify.ts
  src/registerServiceWorker.ts
  src/repositories/chatRepository.ts
  src/repositories/defaultError.ts
  src/repositories/index.ts
  src/repositories/messageRepository.ts
  src/services/chatService.ts
  src/services/client.ts
  src/services/index.ts
  src/services/messageService.ts
  src/shims-tsx.d.ts
  src/shims-vue.d.ts
  src/store/index.ts
  tests/e2e/.eslintrc.js
  tests/e2e/plugins/index.js
  tests/e2e/specs/test.js
  tests/e2e/support/commands.js
  tests/e2e/support/index.js
  tests/unit/example.spec.ts
  tsconfig.json
  vue.config.js
Labels: bug, enhancement

#14 Feature/config ci
  .github/workflows/sonar-scanner.yml
  gulpfile.js
  package-lock.json
  package.json
  public/index.html
  sonar-project.properties
  src/App.vue
  src/assets/logo.svg
  src/components/ChatBox.vue
  src/components/Dashboard.vue
  src/components/HelloWorld.vue
  src/components/index.ts
  src/components/message/Message.vue
  src/entities/chatModel.ts
  src/main.ts
  src/models/chatModel.ts
  src/models/index.ts
  src/models/messageModel.ts
  src/modules/chat/Chat.vue
  src/modules/index.ts
  src/plugins/vuetify.ts
  src/repositories/chatRepository.ts
  src/repositories/defaultError.ts
  src/repositories/index.ts
  src/repositories/messageRepository.ts
  src/services/chatService.ts
  src/services/client.ts
  src/services/index.ts
  src/services/messageService.ts
  tsconfig.json
  vue.config.js
Labels: enhancement

#15 Sprint 3
  .github/workflows/sonar-scanner.yml
  .gitignore
  README.md
  gulpfile.js
  package-lock.json
  package.json
  sonar-project.properties
Labels: release
